#!/usr/bin/env sh

# enact filters on "new" polled messages
notmuch tag +sent -new "tag:new AND ($(cat mysent.q | tr "\n" " "))"

notmuch search --output=messages 'tag:new' > /tmp/msgs
notmuch search --output=files 'tag:new' |\
    bogofilter -o0.7,0.7 -bt |\
    paste - /tmp/msgs |\
    awk '$1 ~ /S/ { print "-new +spam", "-", $3 }' |\
    notmuch tag --batch

# auto tagging
notmuch search --output=messages "tag:new AND ($(cat mybank.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +bank", "-", $1 }' > /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat myclub.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +club", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat mydev.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +dev", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat myedu.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +edu", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat mylist.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +list", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat mylux.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +lux", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat mypol.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +pol", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat mypro.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +pro", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat myshop.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +shop", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat mysrv.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +srv", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat mysub.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +sub", "-", $1 }' >> /tmp/msgs

notmuch search --output=messages "tag:new AND ($(cat myvip.q | tr "\n" " "))" |\
    awk '{ print "-new +inbox +vip", "-", $1 }' >> /tmp/msgs

notmuch search --output=threads 'tag:new' |\
    awk '{ print "-new +inbox", "-", $1 }' >> /tmp/msgs

notmuch search --output=threads "tag:new AND tag:mute" |\
    awk '{ print "-new +mute", "-", $1 }' >> /tmp/msgs

notmuch tag --batch --input=/tmp/msgs
