(("https://www.iaea.org/feeds/topnews" nuc)
 "https://news.mit.edu/rss/topic/mathematics"
 "https://news.mit.edu/rss/topic/nuclear-engineering"
 "https://news.mit.edu/rss/topic/mechanical-engineering"
 "https://news.mit.edu/rss/topic/materials-science-and-engineering"
 "https://news.mit.edu/topic/mitnuclear-power-and-reactors-rss.xml"
 ("https://github.com/LadybirdBrowser/ladybird/tree/master.atom" dev)
 ("https://github.com/FiloSottile/age/tree/main.atom" dev)
 ("https://www.heritage.org/rss" pol)
 ("https://www.ohiogop.org/feed" pol)
 ("https://www.ans.org/news/feed" news)
 ("https://www.economist.com/special-report/rss.xml" news)
 ("https://www.economist.com/finance-and-economics/rss.xml" news)
 ("https://www.economist.com/science-and-technology/rss.xml" news)
 ("https://www.economist.com/middle-east-and-africa/rss.xml" news)
 ("https://www.economist.com/china/rss.xml" news)
 ("https://www.economist.com/britain/rss.xml" news)
 ("https://www.economist.com/europe/rss.xml" news)
 ("https://www.economist.com/united-states/rss.xml" news)
 ("https://www.iaea.org/feeds/pressalerts")
 ("https://www.iaea.org/feeds/dgstatements")
 ("https://www.iaea.org/feeds/photoessays")
 ("https://www.iaea.org/feeds/videos")
 ("https://www.iaea.org/feeds/publications")
 ("https://www.iaea.org/feeds/iaeatalk")
 ("http://feeds.feedburner.com/iaeameetings")
 ("https://www.iaea.org/feeds/fuksuhimastatusreports")
 ("http://feeds.feedburner.com/IaeaJobVacancies" job))
